title: Toby Clark
description: Projects, publications, and assorted notes by Toby Clark.
url: "https://tobybenjaminclark.github.io"
baseurl: "/wiki"
permalink: pretty

author:
  name: Toby Clark

markdown: kramdown

exclude:
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
