title: Toby Clark
description: Publications and assorted notes by Toby Clark.
url: "https://www.toby.wiki"
baseurl: ""
permalink: pretty

author:
  name: Toby Clark

markdown: kramdown
future: true

exclude:
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name/
  oddments:
    output: true
    permalink: /oddments/:name/
  publications:
    output: true
    permalink: /publications/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: oddments
    values:
      layout: entry
  - scope:
      path: ""
      type: publications
    values:
      layout: entry
